#!/usr/bin/env bun
/**
 * Build self-contained host binaries (Bun runtime + host + embedded UI).
 *
 *   bun run packages/host/scripts/build-binaries.ts            # all targets
 *   bun run packages/host/scripts/build-binaries.ts --current  # this machine only
 *   bun run packages/host/scripts/build-binaries.ts --target bun-linux-x64 [--target ...]
 *
 * Output: packages/host/bin/pp-host-<os>-<arch>[.exe]
 *
 * Requires packages/ui/dist (run `bun run build` first). Source maps are not
 * embedded. The generated embedded-ui.ts is restored to its stub afterwards so
 * the tree stays clean.
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";

const hostDir = resolve(import.meta.dir, "..");
const uiDist = resolve(hostDir, "../ui/dist");
const embeddedFile = join(hostDir, "src", "embedded-ui.ts");
const outDir = join(hostDir, "bin");

const ALL_TARGETS: Record<string, string> = {
  "bun-linux-x64": "pp-host-linux-x64",
  "bun-linux-arm64": "pp-host-linux-arm64",
  "bun-darwin-arm64": "pp-host-darwin-arm64",
  "bun-darwin-x64": "pp-host-darwin-x64",
  "bun-windows-x64": "pp-host-windows-x64.exe",
};

function currentTarget(): string {
  const os =
    process.platform === "win32" ? "windows" : process.platform === "darwin" ? "darwin" : "linux";
  const arch = process.arch === "arm64" ? "arm64" : "x64";
  return `bun-${os}-${arch}`;
}

function listFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    if (statSync(p).isDirectory()) out.push(...listFiles(p));
    else if (!p.endsWith(".map")) out.push(p);
  }
  return out;
}

function generateEmbedded(): string {
  const files = listFiles(uiDist).sort();
  const lines = [
    "// GENERATED by scripts/build-binaries.ts - do not edit; restored to a stub after the build.",
  ];
  const entries: string[] = [];
  files.forEach((abs, i) => {
    const rel = relative(uiDist, abs).split("\\").join("/");
    const importPath = relative(join(hostDir, "src"), abs).split("\\").join("/");
    lines.push(
      `import f${i} from "${importPath.startsWith(".") ? importPath : `./${importPath}`}" with { type: "file" };`,
    );
    entries.push(`  ${JSON.stringify(rel)}: f${i},`);
  });
  lines.push("export const embeddedUi: Record<string, string> = {", ...entries, "};", "");
  return `${lines.join("\n")}`;
}

async function main() {
  const argv = process.argv.slice(2);
  let targets = Object.keys(ALL_TARGETS);
  if (argv.includes("--current")) targets = [currentTarget()];
  const explicit = argv.flatMap((a, i) => (a === "--target" && argv[i + 1] ? [argv[i + 1]!] : []));
  if (explicit.length) targets = explicit;
  for (const t of targets) if (!ALL_TARGETS[t]) throw new Error(`unknown target ${t}`);

  if (!existsSync(join(uiDist, "index.html"))) {
    throw new Error(`UI not built (${uiDist}); run \`bun run build\` first`);
  }

  const stub = readFileSync(embeddedFile, "utf8");
  mkdirSync(outDir, { recursive: true });
  writeFileSync(embeddedFile, generateEmbedded());
  try {
    for (const target of targets) {
      const outfile = join(outDir, ALL_TARGETS[target]!);
      console.log(`building ${target} -> ${relative(process.cwd(), outfile)}`);
      const proc = Bun.spawn(
        [
          "bun",
          "build",
          "--compile",
          "--minify",
          `--target=${target}`,
          join(hostDir, "src", "cli.ts"),
          "--outfile",
          outfile,
        ],
        { cwd: hostDir, stdout: "inherit", stderr: "inherit" },
      );
      const code = await proc.exited;
      if (code !== 0) throw new Error(`bun build failed for ${target} (exit ${code})`);
    }
  } finally {
    writeFileSync(embeddedFile, stub);
  }
  console.log("done:", targets.map((t) => ALL_TARGETS[t]).join(", "));
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
